### ISSUE TITLE
关于"如果要以内嵌、内挂/内封的形式分享"，如未修改字幕，是否需要附带呢

### ISSUE THREAD

**Issue by ted423** [tastysugar/SweetSub#1]
三次元pt通常视频不附带字幕比较利于保种。而有些站禁止了种子内附加压缩包
另一方面，修改之后能否通过网盘或者传到伪射手并在帖内发布连接之类的方式？
目前暂不准备使用，但想了解下。

**Comment by tastysugar** [comment]
你如果是转载 SweetSub 已发布的内嵌、内挂视频，不需要附带，也不需要在转载前告诉我。
不过，如果你想用 SweetSub 发布的字幕文件，和你自己的视频源重新压制成内嵌视频，或者重新 remux。该行为被默认协议的 Creative Common BY-NC-ND 4.0 中的 ND（禁止演绎） 所禁止。

而这并不意味着我们完全禁止演绎，如果想要这么做，可以先跟我联系。

**Comment by ted423** [comment]
我看readme里是写的“如果要以内嵌、内挂/内封的形式分享，请附带上修改过的外挂字幕源文件。”
所以实际上，如果需要内嵌、内挂/内封，默认是不允许，需要沟通是吧。
那可能我觉得readme那里需要修正一下？

**Comment by tastysugar** [comment]
你说得对，我应该改一下。

**Comment by tastysugar** [comment]
的确，协议写得不够严谨。
我再仔细研究了下 CC 的说明，内封不应该算是演绎，但是内嵌是演绎。
稍后我会修正一下 readme。
所以压制内嵌视频需要提前打个招呼，而通过内挂/内封不需要。

**Comment by tastysugar** [comment]
我重新修改了 README 文件，并加上了用例。
不再有附带字幕文件的要求。
不知你是否还有疑问。

**Comment by ted423** [comment]
了解了，感谢
