### ISSUE TITLE
国家队字幕报错

### ISSUE THREAD

**Issue by ZeppLu** [tastysugar/SweetSub#1]
在这里报错的话，会比较容易看到吧

https://github.com/tastysugar/SweetSub/blob/2a87b0f161267dee300e771040bce5d48dd24ef9/DARLING%20in%20the%20FRANXX/TV_chs/%5BSweetSub%5D%20DARLING%20in%20the%20FRANXX%20-%2009.chs.ass#L385

Trangle -> Triangle

**Comment by tastysugar** [comment]
谢谢
